[[redirects]]
  from = "/"
  to = "https://greasyfork.org.cn/zh-hans"
  status = 301
  force = true

[[redirects]]
  from = "/zh-hans"
  to = "https://greasyfork.org.cn/zh-hans"
  status = 301
  force = true  

[[redirects]]
  from = "/zh-hans/*"
  to = "https://xdrcgfn.dahi.edu.eu.org/zh-hans/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/redirect/to"
  to = "https://thepage-gfork.zh-hk.eu.org/redirect/to"
  status = 308
  force = true

[[redirects]]
  from = "/redirect/"
  to = "https://thepage-gfork.zh-hk.eu.org/redirect/"
  status = 308
  force = true

[[redirects]]
  from = "/*"
  to = "https://greasyfork.org.cn/:splat"
  status = 307
  force = true
