[[redirects]]
  from = "/"
  to = "https://greasyfork.org.cn/zh-hans"
  status = 301
  force = true

[[redirects]]
  from = "/zh-hans"
  to = "https://greasyfork.org.cn/zh-hans"
  status = 301
  force = true
  
[[redirects]]
  from = "/s"
  to = "https://thepage-gfork.zh-hk.eu.org/searchw"
  status = 200
  force = true
  
[[redirects]]
  from = "/p/1E3F8A9F-DDC6-4D76-B101-5683AA13E349"
  to = "https://dgkkhxhkj.dahi.edu.eu.org/zh-CN/scripts.json"
  status = 308

[[redirects]]
  from = "/ads.txt"
  to = "https://thepage-gfork.zh-hk.eu.org/ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "https://thepage-gfork.zh-hk.eu.org/404"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://thepage-gfork.zh-hk.eu.org/favicon.ico"
  status = 308
  force = true

[[redirects]]
  from = "/*/moderator_actions*"
  to = "/zh-hans"
  status = 307
  force = true  

[[redirects]]
  from = "/*/scripts/481396*"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/scripts/533633*"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/scripts/39828"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/scripts/39828-*"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/scripts/39828/*"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/users/"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/*/scripts/"
  to = "/zh-hans"
  status = 307
  force = true

[[redirects]]
  from = "/zh-hans/help/*"
  to = "https://home.greasyfork.org.cn/zh-hans/help/:splat"
  status = 308
  force = true

[[redirects]]
  from = "/zh-hans/*"
  to = "https://xdrcgfn.dahi.edu.eu.org/zh-hans/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/redirect/to"
  to = "https://greasyfork.org.cn/redirect/to"
  status = 308
  force = true

[[redirects]]
  from = "/redirect/"
  to = "https://greasyfork.org.cn/redirect/"
  status = 308
  force = true

[[redirects]]
  from = "/*"
  to = "https://greasyfork.org.cn/:splat"
  status = 307
